# site settings
title: AI Team
subtitle: a MoMe initiative
email: mehdi.mounsif@modis.com
description: AI autonomy-empowerment for newcomers
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Mehdi Mounsif
street_address: La Pardieu
city: Clermont-Ferrand
state: Rhône-Alpes Auvergne
zip_code: 63000
country: United States of America
phone: +33 6 65 74 74 98 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

kramdown: 
  math_engine: katex
#   math_engine_opts: {} # more info: https://kramdown.gettalong.org/math_engine/mathjax.html
#   preview: false
#   preview_as_code: false 

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
